# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  :wave: Thank you for opening your first issue. I'm just an automated bot that's here to help you get the information you need quicker, so please ignore this message if it doesn't apply to your issue.

  If you're looking for support, you should try the Slack group by registering your email address at https://cachethq-slack.herokuapp.com. Alternatively, email support@alt-three.com for our Professional support service (please note, this a paid service.)

  If you're issue is with documentation, you can suggest edits by clicking the **Suggest Edits** link on any page, or open an issue at https://github.com/CachetHQ/Docs

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Congratulations on opening your first Pull Request, this is a momentous day for you and us! :sparkles:

  To help us out, please make sure that you've followed the below:

  - Non-English translations should be submitted to https://translate.cachethq.io
  - Documentation should be submitted to https://docs.cachethq.io
  - Please make sure that all tests pass!
  - Don't worry about StyleCI, it'll fix itself on merge.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Hooray! Your first Pull Request was merged, here's to many more :rocket:

# It is recommend to include as many gifs and emojis as possible
