name: master

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron:  '00 00 * * 6' # At 12:00 AM, only on Saturday

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Restore dependencies
      run: |
        cd src/atlassian-downloader
        dotnet restore
    - name: Build
      run:  |
        cd src/atlassian-downloader
        dotnet build --no-restore
    - name: Test
      run:  |
        cd src/atlassian-downloader
        dotnet test --no-build --verbosity normal
