name: master

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron:  '00 00 * * 6' # At 12:00 AM, only on Saturday

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Restore
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      run: |
        cd src
        dotnet restore

    - name: Build
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      run:  |
        cd src
        dotnet build --no-restore

    - name: Test
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      run:  |
        cd src
        dotnet test --no-build --verbosity normal
