name: develop

on:
  pull_request:
    branches:
      - '*'
    tags:
      - '*'
  push:
    branches:
      - 'develop'

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Restore
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      run: |
        cd src
        dotnet restore

    - name: Build
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      run:  |
        cd src
        dotnet build --no-restore

    - name: Test
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      run:  |
        cd src
        dotnet test --no-build --verbosity normal
